[package]
name = "wupf"
description = "Wii U Plugin Framework"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/rust-wiiu/wupf"
publish = false

[dependencies]
wut = { path = "https://github.com/rust-wiiu/wut" }
wups = { path = "https://github.com/rust-wiiu/wups" }
