[package]
name = "wupf"
description = "Wii U Plugin Framework"
version = "0.3.2"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/rust-wiiu/wupf"
publish = false

[dependencies]
wut = { git = "https://github.com/rust-wiiu/wut", tag = "v0.3.0" }
wups = { git = "https://github.com/rust-wiiu/wups", tag = "v0.3.2" }
